### ISSUE TITLE
[MMT4] Doesn't start with country code

### ISSUE THREAD

**Issue by EtienneAb3d** [modernmt/modernmt#471] opened 2019-05-06 16:18 UTC
In the latest release, MMT4 doesn't start when having a country code, while it was starting previously:
```
java.lang.IllegalArgumentException: en_GB
	at eu.modernmt.lang.Language.fromString(Language.java:96)
	at eu.modernmt.decoder.neural.ModelConfig.getAvailableModels(ModelConfig.java:68)
	at eu.modernmt.decoder.neural.NeuralDecoder.<init>(NeuralDecoder.java:70)
	at eu.modernmt.engine.Engine.load(Engine.java:105)
	at eu.modernmt.cluster.ClusterNode.start(ClusterNode.java:280)
	at eu.modernmt.facade.ModernMT.start(ModernMT.java:54)
	at eu.modernmt.cli.ClusterNodeMain.main(ClusterNodeMain.java:182)

```

**Comment by nicolabertoldi** [comment] 2019-05-06 16:35
@EtienneAb3d 

The right syntax is en-GB

**Comment by EtienneAb3d** [comment] 2019-05-06 16:43
Oups!
Ok, it starts.
The "memories" API command is not responding, without any message in the LOG. 
:(

**Comment by davidecaroselli** [comment] 2019-05-07 08:50
@EtienneAb3d can you please paste here all the steps needed to reproduce the problem? Without it, we can't help you.

**Comment by EtienneAb3d** [comment] 2019-05-07 09:35
Hmmm... the problem is perhaps not the one it seems. 
I changed all my calls in order to use only language codes without countries, and changed the model config files accordingly.
I still got some blocking states, where MMT4 is no more responding to any kind of call, while it is working properly after being restarted. When blocked, nothing is visible in the LOG file.
Hope I will be able to get more informations in time.
At this moment, it is working.

**Comment by davidecaroselli** [comment] 2019-05-07 09:44
Just a hint: you can start ModernMT server with higher verbosity level. This is useful for debug, of course not for production :)
```bash
./mmt start -v 2   # verbosity: debug
./mmt start -v 3   # verbosity: trace
```

**Comment by EtienneAb3d** [comment] 2019-05-07 09:54
I already started it with option "-v 3". 
But, when blocked, there isn't any information in the LOG.
Possibly, I should have a look at Cassandra LOG ?

**Comment by davidecaroselli** [comment] 2019-05-07 10:19
It really depends on when it blocks.

If you are creating a memory: look at Cassandra, because ModernMT is basically creating a new entry in Cassandra
If you are importing a TMX: look at Kafka, because ModernMT is basically cleaning the TMX and uploading it into Kafka queue.

I suggest also to look at your machine `top`: is it really stuck (no heavy CPU activity) or is it just doing some heavy, long-running work (some process at 80-100% CPU)?

**Comment by EtienneAb3d** [comment] 2019-05-07 11:02
Where can I find Cassandra log? The one I find seems to be a binary with not-displayable chars.

The machine is a bit RAM overloaded, as said in a previous post, because of Fairseq training on the second card. But, this wasn't really a problem with MMT3, for example. CPU and disks are not really loaded.

**Comment by EtienneAb3d** [comment] 2019-05-07 11:53
Ok, found this one:
`runtime/<model>/logs/embedded-cassandra.log`
Now waiting for a new blocking situation..

**Comment by davidecaroselli** [comment] 2019-05-07 12:12
If you're trying to run ModernMT server on the same machine where you're running training **and** you also have Memory Swap activated, then the problem could definitely be the amount of RAM.

**Comment by EtienneAb3d** [comment] 2019-05-07 12:12
Blocked. 
This time, it's on a "translate" URL call, without context (not sure it's always the case).
In this call, the memory is not involved, isn't it ?
It's thus either in MMT4, or Fairseq.
Nothing special displayed in the LOG. The last logged action seems to be a memory deletion:
```
2019-05-07 13:56:49,615 INFO  eu.modernmt.api.ApiServer.Router [qtp2118413714-273] "DELETE /memories/182" 200 12 {"status":200}
2019-05-07 13:56:49,615 DEBUG eu.modernmt.cluster.kafka.KafkaDataManager [DataPollingThread] Loading batch of 1 records: process=true, align=false
2019-05-07 13:56:49,616 DEBUG eu.modernmt.cluster.kafka.KafkaDataManager [DataPollingThread] Delivering batch of 1 updates
2019-05-07 13:56:49,659 INFO  eu.modernmt.cluster.kafka.KafkaDataManager [DataPollingThread] DataBatch delivered of size 1, channels = {0=133}

```

**Comment by EtienneAb3d** [comment] 2019-05-07 12:20
Remark: in my previous post, "memory" refers to the MMT4 TM, not the RAM.

Of course, I will soon test it without the heavy training running.

**Comment by EtienneAb3d** [comment] 2019-05-07 16:37
Even without RAM overload, MMT4 is blocking after a time having working properly. In the LOG, I still get a memory deletion as last action reported.
More than this, the model is bad, after 4 days of training, while it was usually good after 3 days with MMT3.
I will try to train with a small training set, similar to the one I usually build for MMT3. I saw in the training log that MMT4 was looping a large number of times in the steps where it seems to determine the vocab size. I found it very strange. At least, a too large vocab could explain the bad quality of the resulting model: it produces exponentially much more possibilities in the input/output combinations!

**Comment by davidecaroselli** [comment] 2019-05-07 16:50
I will try to replicate the problem deleting a memory, just to be super sure, which steps led you to the system freezing? Have you checked the machine `top`? Are there any running processes with high CPU usage?

Regarding the vocabulary, that is totally expected. The same exact procedure was run in MMT3 but a bug was preventing the logs to be properly outputted.

Regarding the quality, we have our quality boost in large datasets, but I don't see any reason why it shouldn't be the same for smaller sets. My hint is always the same: run the same training (same model size, time, resources and training set) to compare if there are any problems. We are currently running some training too with the latest `version/v4.0` so I will be able to report the results here asap.

**Comment by LoekvanKooten** [comment] 2019-05-07 16:54
@davidecaroselli I finally got MMT4 working, but my initial impressions are the same. I'm not sure whether loss values of MMT3 and MMT4 can be compared directly, but MMT3 would converge at 1 with my English-Dutch dataset, while MMT4 converges at 4 (!). As said, I'm not sure how the values compare, but an intermediate run in a live production environment confirms that the results from MMT4 are far, far worse, to the extent that translating manually is quicker. MMT3 would result in an actual boost.

Results from MMT4 are generated faster.

This is based on a 30 million word corpus.

**Comment by EtienneAb3d** [comment] 2019-05-07 16:59
My process is creating/deleting a memory for each sentence translation, as explain in some other posts (waiting for a way to provide with a set of sentence pairs to tune at translation time). This wasn't a problem with MMT2&3. I don't think you will be able to reproduce without this heavily stressing memory creation/deletion.

**Comment by davidecaroselli** [comment] 2019-05-14 14:44
I'm closing this because the problem was actually the one of issue #484 .
Thanks for your help!

**Closed by davidecaroselli** 2019-05-14 14:44 UTC
