### ISSUE TITLE
List of API supported language codes

### ISSUE THREAD

**Issue by bittlingmayer** [modernmt/modernmt#534] opened 2020-04-29 20:12 UTC
There is a list at https://www.modernmt.com:  
> Albanian, Arabic, Bosnian, Bulgarian, Catalan, Chinese, Chinese Traditional, Croatian, Czech, Danish, Dutch, English, Estonian, Finnish, French, German, Greek, Hebrew, Hungarian, Icelandic, Indonesian, Italian, Japanese, Korean, Latvian, Lithuanian, Macedonian, Malay, Maltese, Norwegian Bokmal, Norwegian Nynorsk, Polish, Portuguese, Portuguese Brazil, Romanian, Russian, Serbian Latin, Slovak, Slovenian, Spanish, Spanish Latin America, Swedish, Thai, Turkish, Ukrainian, Vietnamese. 

There is a list at https://github.com/modernmt/modernmt/blob/2bbad392209d900c3290a88d7217eef72bee22a3/src/textprocessing/src/main/java/eu/modernmt/cleaning/filters/lang/OptimaizeLanguageFilter.java
```
    private static final HashSet<String> SUPPORTED_LANGUAGES = new HashSet<>(
            Arrays.asList("af", "an", "ar", "ast", "be", "br", "ca", "bg", "bn", "cs", "cy", "da", "de", "el", "en",
                    "es", "et", "eu", "fa", "fi", "fr", "ga", "gl", "gu", "he", "hi", "hr", "ht", "hu", "id", "is",
                    "it", "ja", "km", "kn", "ko", "lt", "lv", "mk", "ml", "mr", "ms", "mt", "ne", "nl", "no", "oc",
                    "pa", "pl", "pt", "ro", "ru", "sk", "sl", "so", "sq", "sr", "sv", "sw", "ta", "te", "th", "tl",
                    "tr", "uk", "ur", "vi", "wa", "yi", "zh"));
```

But the two lists are not the same.  The second list has codes like `ast` for Asturian, which is not included in the other list.  There are always some nuances around languages with variants, like Chinese, Spanish, Portuguese and Norwegian, sometimes an API requires the variant when a target language but combines them when a source language, so it would be good to have the actual list and definitive wording on questions like whether `pt` is supported and whether it defaults to `pt-BR` or `pt-PT`.

The right place would be https://www.modernmt.com/api/ under *General aspects*, as languages are used by many API calls.

**Comment by davidecaroselli** [comment] 2020-04-30 16:03
Hi @bittlingmayer ,

there is a bit of confusion here, at it is definitely our fault. The problem is that in the could-based service documentation, an important API is missing: https://api.modernmt.com/languages
The result is the complete list of language combinations supported by the cloud service - we will add that API as soon as possible to the online docs.

However, please notice that the cloud service and the open-source technology **are two distinct and different things**.

ModernMT open-source is a "technology" for machine translation, so it does not have a "list" of supported languages. In fact, the languages a ModernMT engine supports depend exclusively n how many (and which) models you have trained. If I want to support English-to-Italian and French-to-English you need to use ModernMT open-source to train **2 models** on your data en-it and fr-en.

The ModernMT cloud service is a service that uses the ModernMT machine translation technology with some enhancements **plus** a large number of models trained on billions of high-quality parallel text. So ModernMT cloud service offers the language combinations for which we have trained and provided a neural model.

Finally, that list you found at `OptimaizeLanguageFilter.java` is just the list of languages supported **by the OptimaizeLanguageFilter component**, which is a text filter we use during training to remove sentences in a wrong language. So they are not correlated to languages supported for translation.

I hope I have covered all your points! I'm closing this issue right now just because is not really related to ModernMT open-source and because it can create confusion by mixing the two different things. Anyways, feel free to post new messages if I have not answered completely.

**Closed by davidecaroselli** 2020-04-30 16:03 UTC

**Comment by bittlingmayer** [comment] 2020-05-01 07:20
Thanks, Davide, makes sense.
